# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-uuid/Makefile 417719 2016-06-28 14:00:45Z mat $

PORTNAME=	uuid
PORTVERSION=	1.0.4
CATEGORIES=	devel pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	UUID extension in PHP

LICENSE=	LGPL3

LIB_DEPENDS=	libuuid.so:misc/e2fsprogs-libuuid

USES=		php:ext tar:tgz

.include <bsd.port.mk>
