# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-uuid/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	uuid
PORTVERSION=	1.0.4
PORTREVISION=	1
CATEGORIES=	devel pear

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	UUID extension in PHP

LICENSE=	LGPL3

LIB_DEPENDS=	libuuid.so:misc/e2fsprogs-libuuid

USES=		php:pecl

.include <bsd.port.mk>
