# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-qb/Makefile 430631 2017-01-05 11:00:49Z amdmi3 $

PORTNAME=	qb
PORTVERSION=	2.4.0
PORTREVISION=	3
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PHP Accelerator designed mainly for graphic work

LICENSE=	PHP301

USES=		php:ext tar:tgz
USE_GCC=	any
IGNORE_WITH_PHP=	70

.include <bsd.port.mk>
