# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/pecl-intl/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	intl
PORTVERSION=	3.0.0
PORTREVISION=	7
CATEGORIES=	devel pear

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	PECL extension to support Internationalization(ICU)

LICENSE=	PHP301

LIB_DEPENDS=	libicui18n.so:devel/icu

IGNORE_WITH_PHP=70 71
USES=		php:pecl

.include <bsd.port.mk>
