# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/php-scalar_objects/Makefile 419514 2016-08-03 12:47:05Z mat $

PORTNAME=	scalar_objects
PORTVERSION=	0.0.20140124
PORTREVISION=	2
CATEGORIES=	devel
PKGNAMEPREFIX=	php-

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Support method calls on primitive types in PHP

LICENSE=	PHP301

USE_GITHUB=	yes
GH_ACCOUNT=	nikic
GH_TAGNAME=	baf4985

USES=		php:ext
IGNORE_WITH_PHP=	70

.include <bsd.port.mk>
