# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD$

PORTNAME=	grpc
PORTVERSION=	0.0.0.20150623
CATEGORIES=	devel
PKGNAMEPREFIX=	go-

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	RPC library for Go

LICENSE=	BSD3CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	grpc
GH_PROJECT=	${PORTNAME}-go
GH_TAGNAME=	389d18d

GO_PKGNAME=	google.golang.org/${PORTNAME}

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/lang/go/files/bsd.go.mk"
.include <bsd.port.post.mk>
