# Created by: Marcus Alves Grando <mnag@FreeBSD.org>
# $FreeBSD: head/misc/pecl-timezonedb/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	timezonedb
PORTVERSION=	2016.10
CATEGORIES=	misc

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Timezone Database to be used with PHP date and time functions

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

CONFIGURE_ARGS=	--enable-timezonedb
USES=		php:pecl

.include <bsd.port.mk>
