# Created by: Marcus Alves Grando <mnag@FreeBSD.org>
# $FreeBSD: head/misc/pecl-timezonedb/Makefile 465610 2018-03-26 16:35:26Z sunpoet $

PORTNAME=	timezonedb
PORTVERSION=	2018.4
CATEGORIES=	misc

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Timezone Database to be used with PHP date and time functions

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

CONFIGURE_ARGS=	--enable-timezonedb
USES=		php:pecl

.include <bsd.port.mk>
