# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-json_post/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	json_post
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	JSON POST handler in PHP

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		php:pecl
USE_PHP=	json:build

.include <bsd.port.mk>
