# Created by: Stanislav Svirid <count@211.ru>
# $FreeBSD: head/net/py-netifaces/Makefile 428497 2016-12-13 15:20:48Z amdmi3 $

PORTNAME=	netifaces
PORTVERSION=	0.10.5
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	count@211.ru
COMMENT=	Getting network addresses from Python

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
