# Created by: Stanislav Svirid <count@211.ru>
# $FreeBSD: head/net/py-netifaces/Makefile 366498 2014-08-29 10:44:09Z bapt $

PORTNAME=	netifaces
PORTVERSION=	0.10.4
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	count@211.ru
COMMENT=	Getting network addresses from Python

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
