# Created by: Jens Rehsack <rehsack@liwing.de>
# $FreeBSD: head/devel/php-xdebug/Makefile 417719 2016-06-28 14:00:45Z mat $

PORTNAME=	xdebug
PORTVERSION=	2.4.0
CATEGORIES=	devel
MASTER_SITES=	https://xdebug.org/files/
PKGNAMEPREFIX=	php-

MAINTAINER=	freebsd-ports-maintainers@intermedix.com
COMMENT=	Xdebug extension for PHP

LICENSE=	PHP30

CONFIGURE_ARGS=	--enable-xdebug
USES=		php:zend tar:tgz

SUB_FILES=	pkg-message

.include <bsd.port.mk>
