# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-channel-symfony2/Makefile 429663 2016-12-27 21:19:22Z rakuco $

PORTNAME=	symfony2
PORTVERSION=	20110826
PORTREVISION=	2
CATEGORIES=	devel www pear

MAINTAINER=	joneum@bsdproject.de
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.symfony.com

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
