# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-channel-symfony2/Makefile 463949 2018-03-09 09:26:52Z mat $

PORTNAME=	symfony2
PORTVERSION=	20110826
PORTREVISION=	2
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.symfony.com

.include "${.CURDIR}/../../devel/pear/bsd.pear.channel.mk"
.include <bsd.port.mk>
