# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD$

PORTNAME=	Translation
PORTVERSION=	${SYMFONY2_PORTVERSION}
CATEGORIES=	devel pear
PKGNAMEPREFIX=	pear-Symfony_Component_

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Symfony2 Translation Component

LICENSE=	MIT

IGNORE_WITH_PHP=4 52

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-symfony2/bsd.symfony2.mk"
.include <bsd.port.post.mk>
