# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-uopz/Makefile 456296 2017-12-14 13:57:28Z tz $

PORTNAME=	uopz
PORTVERSION=	2.0.7
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	User Operations for PHP Zend engine

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	70 71 72

.include <bsd.port.mk>
