# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-uopz/Makefile 372116 2014-11-03 16:35:51Z pawel $

PORTNAME=	uopz
PORTVERSION=	2.0.6
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	User Operations for PHP Zend engine

LICENSE=	PHP301

USE_PHP=	yes
USE_PHPEXT=	yes
USES=		tar:tgz
IGNORE_WITH_PHP=	53

.include <bsd.port.mk>
