# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-request/Makefile 456296 2017-12-14 13:57:28Z tz $

PORTNAME=	request
PORTVERSION=	1.0.0b1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Provides server-side request and response objects for PHP 7

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		php:pecl
IGNORE_WITH_PHP=	56 72

.include <bsd.port.mk>
