# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-request/Makefile 429244 2016-12-23 10:50:57Z vanilla $

PORTNAME=	request
PORTVERSION=	1.0.0b1
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Provides server-side request and response objects for PHP 7

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		php:ext tar:tgz
IGNORE_WITH_PHP=	56

.include <bsd.port.mk>
