# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-hrtime/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	hrtime
PORTVERSION=	0.6.0
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	High resolution timing for PHP

LICENSE=	BSD2CLAUSE

USES=		php:pecl

.include <bsd.port.mk>
