# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-hrtime/Makefile 417719 2016-06-28 14:00:45Z mat $

PORTNAME=	hrtime
PORTVERSION=	0.5.1
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	High resolution timing for PHP

LICENSE=	BSD2CLAUSE

USES=		php:ext tar:tgz

.include <bsd.port.mk>
