# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-uri_template/Makefile 456296 2017-12-14 13:57:28Z tz $

PORTNAME=	uri_template
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	URI Template(RFC6570) library for PHP

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	70 71 72

.include <bsd.port.mk>
