# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-uri_template/Makefile 417719 2016-06-28 14:00:45Z mat $

PORTNAME=	uri_template
PORTVERSION=	1.0
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
EXTRACT_SUFX=	.tgz
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	URI Template(RFC6570) library for PHP

LICENSE=	PHP301

USES=		php:ext
IGNORE_WITH_PHP=	70

.include <bsd.port.mk>
