# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-jsmin/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	jsmin
PORTVERSION=	2.0.1
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PHP extension for minifying JavaScript

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	70

.include <bsd.port.mk>
