# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-jsmin/Makefile 461633 2018-02-12 19:04:55Z sunpoet $

PORTNAME=	jsmin
PORTVERSION=	3.0.0
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PHP extension for minifying JavaScript

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=56

.include <bsd.port.mk>
