# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-channel-phpdoc/Makefile 463949 2018-03-09 09:26:52Z mat $

PORTNAME=	phpdoc
PORTVERSION=	20120214
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.phpdoc.org

.include "${.CURDIR}/../../devel/pear/bsd.pear.channel.mk"
.include <bsd.port.mk>
