# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-PHP_Depend/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	PHP_Depend
PORTVERSION=	1.1.2
CATEGORIES=	devel pear
MASTER_SITES=	http://pear.pdepend.org/get/

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP_Depend design quality metrics for PHP packages

LICENSE=	BSD3CLAUSE

USES=	pear
PEAR_CHANNEL=	pdepend
USE_PHP=	dom tokenizer simplexml

.include <bsd.port.mk>
