# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-Pirum/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	Pirum
PORTVERSION=	1.1.5
CATEGORIES=	devel www pear
MASTER_SITES=	http://pear.pirum-project.org/get/

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Simple PEAR channel server manager

LICENSE=	MIT

PEAR_CHANNEL=	pirum
USES=	pear

.include <bsd.port.mk>
