# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD$

PORTNAME=	MonologBridge
PORTVERSION=	2.3.4
CATEGORIES=	devel pear
PKGNAMEPREFIX=	pear-Symfony_Bridge_

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Symfony2 MonologBridge Component

LICENSE=	MIT

USE_SYMFONY2_RUN=	Symfony_Component_HttpKernel
IGNORE_WITH_PHP=52

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-symfony2/bsd.symfony2.mk"
.include <bsd.port.post.mk>
