# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/chinese/php-opencc/Makefile 428730 2016-12-17 12:53:14Z sunpoet $

PORTNAME=	opencc
PORTVERSION=	0.0.0.20161110
CATEGORIES=	chinese
PKGNAMEPREFIX=	php-

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	OpenCC shared extension for php

LICENSE=	PHP301

LIB_DEPENDS=	libopencc.so:chinese/opencc

USE_GITHUB=	yes
GH_ACCOUNT=	NauxLiu
GH_PROJECT=	opencc4php
GH_TAGNAME=	8007639

USES=		php:ext

.include <bsd.port.mk>
