# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD$

PORTNAME=	php-opencc
PORTVERSION=	0.0.0.20161110
CATEGORIES=	chinese

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	OpenCC shared extension for php

LICENSE=	PHP301

LIB_DEPENDS=	libopencc.so:chinese/opencc

USE_GITHUB=	yes
GH_ACCOUNT=	NauxLiu
GH_PROJECT=	opencc4php
GH_TAGNAME=	8007639
PHP_MODNAME=	opencc

USES=	php:ext tar:tgz

.include <bsd.port.mk>
