# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD$

PORTNAME=	http2
PORTVERSION=	0.0.0.20150510
CATEGORIES=	devel
PKGNAMEPREFIX=	go-

MAINTAINER=	gasol.wu@gmail.com
COMMENT=

LICENSE=	BSD3CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	bradfitz
GH_TAGNAME=	f8202bc9

GO_PKGNAME=	github.com/${GH_ACCOUNT}/${GH_PROJECT}

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/lang/go/files/bsd.go.mk"
.include <bsd.port.post.mk>
