# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-Symfony_Component_Finder/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	Finder
PORTVERSION=	2.4.4
CATEGORIES=	devel pear
MASTER_SITES=	http://pear.symfony.com/get/
PKGNAMEPREFIX=	${PEAR_PKGNAMEPREFIX}Symfony_Component_
DIST_SUBDIR=	Symfony2

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Symfony2 Finder Component

LICENSE=	MIT

USES=		pear
PEAR_CHANNEL=	symfony2

.include <bsd.port.mk>
