# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/devel/pear-Net_Gearman/Makefile 369068 2014-09-23 15:15:04Z bapt $

PORTNAME=	Net_Gearman
PORTVERSION=	0.2.3
PORTREVISION=	2
CATEGORIES=	devel pear

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Gearman client libraray for PHP

LICENSE=	BSD2CLAUSE

BUILD_DEPENDS=	${LOCALBASE}/share/pear/PEAR.php:${PORTSDIR}/devel/pear
RUN_DEPENDS=	${LOCALBASE}/share/pear/PEAR.php:${PORTSDIR}/devel/pear

USE_PHP=	json mbstring
USES=		pear

.include <bsd.port.mk>
