# Created by: chinsan
# $FreeBSD: head/devel/pecl-vld/Makefile 374670 2014-12-13 18:30:01Z pawel $

PORTNAME=	vld
PORTVERSION=	0.13.0
CATEGORIES=	devel pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Dump the internal representation of PHP scripts

LICENSE=	BSD2CLAUSE

USES=		tar:tgz
USE_PHP=	yes
USE_PHPEXT=	yes

CONFIGURE_ARGS=	--enable-vld

.include <bsd.port.mk>
