# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-ev/Makefile 370568 2014-10-10 10:10:52Z robak $

PORTNAME=	ev
PORTVERSION=	0.2.13
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	johnpupu@gmail.com
COMMENT=	Libev extension for PHP

LICENSE=	PHP301

USES=		tar:tgz
USE_PHP=	yes
USE_PHP_BUILD=	yes
USE_PHPIZE=	yes
USE_PHPEXT=	yes
IGNORE_WITH_PHP=52 53

.include <bsd.port.mk>
