# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-ev/Makefile 433757 2017-02-09 18:06:14Z krion $

PORTNAME=	ev
PORTVERSION=	1.0.4
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	johnpupu@gmail.com
COMMENT=	Libev extension for PHP

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		php:ext tar:tgz

.include <bsd.port.mk>
