# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD$

PORTNAME=	BrowserKit
PORTVERSION=	${SYMFONY2_PORTVERSION}
CATEGORIES=	devel pear
PKGNAMEPREFIX=	pear-Symfony_Component_

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Symfony2 BrowserKit Component

USE_SYMFONY2_RUN=	Symfony_Component_DomCrawler

LICENSE=	MIT

IGNORE_WITH_PHP=52

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-symfony2/bsd.symfony2.mk"
.include <bsd.port.post.mk>
