# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-jsond/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	jsond
PORTVERSION=	1.3.0
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	JavaScript Object Notation in PHP

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	70

.include <bsd.port.mk>
