# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-jsond/Makefile 464530 2018-03-14 20:30:40Z joneum $

PORTNAME=	jsond
DISTVERSION=	1.4.0
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	JavaScript Object Notation in PHP

LICENSE=	PHP301

USES=		php:pecl

.include <bsd.port.mk>
