# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/security/pecl-libsodium/Makefile 452629 2017-10-22 10:09:33Z vsevolod $

PORTNAME=	libsodium
PORTVERSION=	1.0.6
PORTREVISION=	1
CATEGORIES=	security

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PHP wrapper for the Sodium cryptographic library

LICENSE=	BSD2CLAUSE

LIB_DEPENDS=	libsodium.so:security/libsodium

USES=		php:pecl

.include <bsd.port.mk>
