# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/security/pecl-libsodium/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	libsodium
PORTVERSION=	1.0.6
CATEGORIES=	security

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PHP wrapper for the Sodium cryptographic library

LICENSE=	BSD2CLAUSE

LIB_DEPENDS=	libsodium.so:security/libsodium

USES=		php:pecl

.include <bsd.port.mk>
