# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-sync/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	sync
PORTVERSION=	1.1.0
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Named and unnamed synchronization objects in PHP

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		php:pecl

.include <bsd.port.mk>
