# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-sync/Makefile 428557 2016-12-14 11:38:37Z amdmi3 $

PORTNAME=	sync
PORTVERSION=	1.1.0
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Named and unnamed synchronization objects in PHP

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		php:ext tar:tgz

.include <bsd.port.mk>
