# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-sync/Makefile 417719 2016-06-28 14:00:45Z mat $

PORTNAME=	sync
PORTVERSION=	1.0.1
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
EXTRACT_SUFX=	.tgz
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Named and unnamed synchronization objects in PHP

LICENSE=	MIT

USES=		php:ext
IGNORE_WITH_PHP=	70

.include <bsd.port.mk>
