# Created by: Conor McDermottroe <ports@mcdermottroe.com>
# $FreeBSD: head/devel/pecl-xhprof/Makefile 456296 2017-12-14 13:57:28Z tz $

PORTNAME=	xhprof
PORTVERSION=	0.9.4
PORTREVISION=	1
CATEGORIES=	devel pear

MAINTAINER=	ports@mcdermottroe.com
COMMENT=	Hierarchical Profiler for PHP

LICENSE=	APACHE20

WRKSRC_SUBDIR=		extension

USES=		php:pecl
ONLY_FOR_ARCHS=	i386 amd64
IGNORE_WITH_PHP=	70 71 72

.include <bsd.port.mk>
