# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD$

PORTNAME=	strict
PORTVERSION=	0.3.0
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
EXTRACT_SUFX=	.tgz
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Strict scalar parameter type hint support for 5.4+

LICENSE=	PHP301

USE_PHP=	yes
USE_PHPEXT=	yes

.include <bsd.port.mk>
