# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-strict/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	strict
PORTVERSION=	0.4.1
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Strict scalar parameter type hint support for 5.4+

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	70

.include <bsd.port.mk>
