# Created by: vanilla@
# $FreeBSD: head/devel/pecl-grpc/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	grpc
PORTVERSION=	1.2.0
CATEGORIES=	devel net

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	High performance, general RPC framework

LICENSE=	BSD3CLAUSE

USES=		php:pecl

.include <bsd.port.mk>
