# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: head/devel/pear-channel-doctrine/Makefile 463949 2018-03-09 09:26:52Z mat $

PORTNAME=	doctrine
PORTVERSION=	20130618
CATEGORIES=	devel www pear

MAINTAINER=	wg@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.doctrine-project.org

.include "${.CURDIR}/../../devel/pear/bsd.pear.channel.mk"
.include <bsd.port.mk>
