# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-ezc_Base/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	Base
PORTVERSION=	1.8
CATEGORIES=	devel pear
MASTER_SITES=	http://components.ez.no/get/
PKGNAMEPREFIX=	${PEAR_PKGNAMEPREFIX}${PEAR_CHANNEL}_

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Base package that all ezc components packages rely on

LICENSE=	BSD3CLAUSE

PEAR_CHANNEL=	ezc
USES=	pear

.include <bsd.port.mk>
