# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: head/devel/py-futures/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	futures
PORTVERSION=	3.0.3
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Backport of the concurrent.futures package from Python 3.2

LICENSE=	BSD2CLAUSE

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
