# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/pear-PHP_CodeSniffer/Makefile 417005 2016-06-17 12:43:05Z tz $

PORTNAME=	PHP_CodeSniffer
PORTVERSION=	2.6.1
CATEGORIES=	devel www pear

MAINTAINER=	tz@FreeBSD.org
COMMENT=	PHP Script Tokenises and Sniffs PHP and JavaScript code

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USES=		pear
USE_PHP=	ctype simplexml tokenizer xmlwriter

.include <bsd.port.mk>
