# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: head/devel/pear-Symfony_Component_Console/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	Console
PORTVERSION=	2.4.4
CATEGORIES=	devel pear
MASTER_SITES=	http://pear.symfony.com/get/
PKGNAMEPREFIX=	${PEAR_PKGNAMEPREFIX}Symfony_Component_
DIST_SUBDIR=	Symfony2

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Symfony2 Console Component

LICENSE=	MIT

USES=		pear
PEAR_CHANNEL=	symfony2

.include <bsd.port.mk>
