# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/net/pecl-yp/Makefile 456296 2017-12-14 13:57:28Z tz $

PORTNAME=	yp
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	net pear

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	YP/NIS functions binding for PHP

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	70 71 72

.include <bsd.port.mk>
